### ISSUE TITLE
Core_User_TDD

### ISSUE THREAD

**Issue by Fei-D20** [WojciechWirowski/EASV.CS20B.FW.WorkScheduleProject#1]
1. Here I have a question: should we need the user to contain a password and a hashed password? Because we only need the password in the security part. So maybe in the core the user only needs id, name/email, type is enough. and the hashed password will be in the databases entity, the password will be in the loginUserDto
2. And Also I would like to ask should we make the user Role as Enum or just String?

**Comment by WojciechWirowski** [comment]
1.I will delete them,
2. I think it would be little overkill if we make enum for 2 Role's

**Comment by WojciechWirowski** [comment]
for now I marked them as "?" values :/
